name: capp
description: This tool is perfect for creating console apps, offering widgets for Console elements, input handling, Help generation, argument events, and option configuration
version: 1.1.1
homepage: https://webapp.uproid.com/
repository: https://github.com/uproid/capp.git
issue_tracker: https://github.com/uproid/capp/issues

platforms:
  web:
  linux:
  windows:
  macos:
  android:
  ios: 

topics:
  - cmd
  - console
  - terminal
  - command
  
sdk:
  dart:
  flutter:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.25.8
dependencies: 
  dart_console: ^4.1.1

