name: capp
description: This tool is ideal for creating console applications, with widgets for necessary Console elements, user input handling, Help generation, event handling for arguments, and option configuration.

version: 1.0.0
homepage: https://webapp.uproid.com/
repository: https://github.com/uproid/capp.git
issue_tracker: https://github.com/uproid/capp/issues

platforms:
  web:
  linux:
  windows:
  macos:
  android:
  ios: 

topics:
  - cmd
  - console
  - terminal
  - command
  
sdk:
  dart:
  flutter:

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.25.8

